### ISSUE TITLE
Implement Utilities RFC0005: Source Removal Buildpack

### ISSUE THREAD

**Issue by ryanmoran** [paketo-buildpacks/rfcs#182]
[RFC](https://github.com/paketo-buildpacks/rfcs/blob/main/text/utilities/0005-source-removal-buildpack.md)

## Summary

Adopt [ForestEckhardt's Source Removal buildpack](https://github.com/ForestEckhardt/source-removal) into the Paketo Project to allow for uniform source removal logic across all buildpacks that require such functionality.

**Comment by ForestEckhardt** [comment]
This is completed https://registry.buildpacks.io/buildpacks/paketo-buildpacks/source-removal
