### ISSUE TITLE
Implement RFC0045: Secure runtime environments

### ISSUE THREAD

**Issue by ryanmoran** [paketo-buildpacks/rfcs#188]
[RFC](https://github.com/paketo-buildpacks/rfcs/blob/main/text/0045-user-ids.md)

## Summary
This RFC recommends that Paketo Buildpacks should in general strive to avoid making run-time modifications to the Buildpacks layers or the application directory by default. Instead, they should consider the output image to be read-only by default and explicitly set the parts that need to be writeable during runtime.

## Implementation
At a high level this would involve the following - 

1. Create base stacks equivalent to the current Paketo stacks but with different runtime user ids. Alternatively, we can also target the next Ubuntu/RHEL-UBI based Paketo stacks to contain a different build/runtime user id.
  https://github.com/paketo-buildpacks/stacks/issues/133
1. Run a parallel test pipeline which is optional and allowed to fail for each buildpack. This pipeline should utilize this new builders to gather the level of compliance for the current set of buildpacks. These tests should also provide appropriate directories for writing ephemeral files during runtime such as `/tmp` or `/run`. We can also use docker to mimic read only directories per https://www.thorsten-hans.com/read-only-filesystems-in-docker-and-kubernetes/
1. Track the compliance status and update buildpacks as necessary to comply with this RFC. The majority changes that would be needed would be for runtime executables/scripts provided by buildpacks such as `profile.d` or `exec.d` interfaces. Seperately we would also need to track configuration locations for configurations provided by buildpacks which lead to files being written on the root filesystem, such as log files etc. and configure them to write to ephemeral locations such as `/tmp` or the runtime user's home directory.
1. We should create a utility buildpack that allows users to specific path patterns in `gitignore` format to make such directories group writable.
1. Once all buildpacks comply, we can release the new set of builders/stacks with hardened security environments to Paketo users. - At some point in the future we can deprecate the current less-secure builders and stacks.

**Comment by fg-j** [comment]
Current status: We believe that Paketo buildpacks are all now set up to create images that run successfully on read-only runtime filesystems. We will not be able to integration test this functionality for buildpacks until they are compatible with the Jammy stack. Therefore, closing this issue is blocked on https://github.com/orgs/paketo-buildpacks/projects/24/views/1.
