### ISSUE TITLE
Add dependency license metadata to non-java dependencies

### ISSUE THREAD

**Issue by kvedurmu** [paketo-buildpacks/rfcs#19]
The Java Buildpacks currently add license information to all dependencies in the buildpack (e.g https://github.com/paketo-buildpacks/bellsoft-liberica/blob/main/buildpack.toml#L66-L68). This is pretty useful information to surface in BOM output to users. 

We should add the same metadata (license type and license URI) to non-java buildpacks. Just filing this as a placeholder that we can move over into the dep-server repo once https://github.com/paketo-buildpacks/rfcs/pull/18 is accepted.

**Comment by ForestEckhardt** [comment]
We are picking this up and going to put forward an RFC to add this information to the dep-server metadata. We will make sure to link this issue when the PR is created for the RFC.
