### ISSUE TITLE
Rename of aspnet-core in dotnet-core RFC 0001 might be problematic

### ISSUE THREAD

**Issue by macsux** [paketo-buildpacks/rfcs#216]
Currently RFC0001 for .NET core buildpack renames `dotnet-aspnetcore` to `dotnet-aspnet`. I highly suggest not doing this as it will cause potential future conflicts for legacy ASP.NET buildpacks (the one that only runs on .NET framework). Any drop of "core" is purely on marketing side (in few places - most still refer to it as asp.net core even on Microsoft docs for latest version), but technology codes still carry the core suffix in all product identity codes and is unlikely to change.

**Comment by sophiewigmore** [comment]
@macsux [.NET Core RFC 0001](https://github.com/paketo-buildpacks/rfcs/blob/3979be0a753e27a81dd5bf10fc69d64a9847147e/text/dotnet-core/rfcs/0001-restructure.md) has already been implemented. The line that specifies `provides: dotnet-aspnet` just represents the internal buildpack API (not user-facing really). Anyways, in the [actual implementation ](https://github.com/paketo-buildpacks/dotnet-core-aspnet/blob/ec9dddf90369f04f45d951678a80154a9a8bf6a4/detect.go#L56), `dotnet-aspnetcore` was used, so the RFC has a typo.

**Comment by sophiewigmore** [comment]
@macsux [.NET Core RFC 0001](https://github.com/paketo-buildpacks/rfcs/blob/3979be0a753e27a81dd5bf10fc69d64a9847147e/text/dotnet-core/rfcs/0001-restructure.md) has already been implemented. In the [actual implementation ](https://github.com/paketo-buildpacks/dotnet-core-aspnet/blob/ec9dddf90369f04f45d951678a80154a9a8bf6a4/detect.go#L56), `dotnet-aspnetcore` was used, so the RFC has a typo.
