### ISSUE TITLE
Implement RFC0051: Graceful Stack Upgrades

### ISSUE THREAD

**Issue by ryanmoran** [paketo-buildpacks/rfcs#237]
[RFC](https://github.com/paketo-buildpacks/rfcs/blob/main/text/0052-graceful-stack-upgrades.md)

## Summary

All Paketo Buildpacks should support graceful stack upgrades between the current Bionic and Jammy stacks. For most buildpacks, this should not require any changes, but for some buildpacks, layers created in previous builds that would normally be reused should be recreated if the stack ID changes.

## Supporting Buildpacks

* [x] https://github.com/paketo-buildpacks/dotnet-core/issues/765
* [x] https://github.com/paketo-buildpacks/go/issues/651
* [x] https://github.com/paketo-buildpacks/java/issues/741
* [x] https://github.com/paketo-buildpacks/java-native-image/issues/442
* [x] https://github.com/paketo-buildpacks/nodejs/issues/636
* [x] https://github.com/paketo-buildpacks/php/issues/572
* [x] https://github.com/paketo-buildpacks/python/issues/509
* [x] https://github.com/paketo-buildpacks/ruby/issues/819
* [x] https://github.com/paketo-buildpacks/web-servers/issues/113

**Comment by robdimsdale** [comment]
Python is marked complete with no action taken. We could not find any situations where stack upgrades invalidated the cache, so we will not clear the cache on stack upgrades.

**Comment by fg-j** [comment]
Blocked on completion of Jammy support for PHP and Ruby.

**Comment by sophiewigmore** [comment]
All language families have been released with this functionality
