### ISSUE TITLE
Implement RFC 0053: Create Static Jammy Buildpackless Builder

### ISSUE THREAD

**Issue by sophiewigmore** [paketo-buildpacks/rfcs#263]
In https://github.com/paketo-buildpacks/rfcs/blob/main/text/0053-add-static-stack.md, the creation of a new static stack, and related buildpackless builder were introduced.

Since then, the Jammy static stack has been created: https://github.com/paketo-buildpacks/jammy-static-stack. In order to make this a more useable addition, we should implement the buildpackless static builder as described in the RFC.

Per the RFC:

> The builders team will create a new Github repository at: paketo-buildpacks/builder-jammy-buildpackless-static similar to existing buildpackless builders.

**Comment by sophiewigmore** [comment]
cc @paketo-buildpacks/builders-maintainers

**Comment by robdimsdale** [comment]
@sophiewigmore i think we were holding off on creating a buildpackless builder until we validated that the stack was usable by any of our supported buildpack.

I started exploring integration with Go (see this [slack thread](https://paketobuildpacks.slack.com/archives/CUEGB5FD1/p1664808922468969)) but I ran into some Go-specific issues and deprioritized the investigation. I didn't try Rust, which is the other language I'd expect to work on the scratch stack. I'm not 100% sure if Java Native would work on static or not - I'm not familiar enough with that ecosystem.

If we don't ever get to the point of integrating the static stack with Paketo Buildpacks, even a buildpackless-builder seems like a bit of overkill.

Was there something specific you were looking to achieve with a buildpackless builder, or were you just trying to ensure the RFC was fully implemented?

**Comment by sophiewigmore** [comment]
@robdimsdale I didn't see that thread, that makes sense though. The goal of this issue was to make sure the RFC gets fully implemented. Whether the resolution is to re-explore this or to opt not to go through with a builder, it'll be good to have an easily-discoverable record of that decision.

**Comment by robdimsdale** [comment]
This is an example of where a static builder would be useful: https://github.com/paketo-community/rust/issues/288

**Comment by robdimsdale** [comment]
Give the above use-case of a community member trying to build a statically-linked self-contained rust app, and given the relatively low-cost of maintaining this builder, I think it's worth prioritizing the creation (and ongoing maintenance) of this builder.

**Comment by robdimsdale** [comment]
Repo created at: https://github.com/paketo-buildpacks/builder-jammy-buildpackless-static

**Comment by robdimsdale** [comment]
Automation is hooked up and the first release of the builder has been created: https://github.com/paketo-buildpacks/builder-jammy-buildpackless-static/releases/v0.0.1. I'll close this issue now as the builder is usable via `paketobuildpacks/builder-jammy-buildpackless-static`.
