### ISSUE TITLE
Implement RFC0023 Git Buildpack

### ISSUE THREAD

**Issue by fg-j** [paketo-buildpacks/rfcs#45]
RFC0023: https://github.com/paketo-buildpacks/rfcs/blob/main/accepted/0023-git-buildpack.md

This RFC has been accepted. This issue is a placeholder for implementing the buildpack outlined in the RFC above. The issue can be transferred once the buildpack's repository is created.

**Comment by genevieve** [comment]
Hey! I've implemented the git buildpack according to the rfc. It only has the REVISION var as discussed but if there are others that we want to add, I'd be happy to implement them as well.

https://github.com/genevieve/git

**Comment by ForestEckhardt** [comment]
@ryanmoran Do we need an RFC to pull in @genevieve buildpack or is that encompassed by the existing RFC?

**Comment by ryanmoran** [comment]
Its covered by the existing RFC. It shouldn't matter if the contribution is from a Utility buildpack team member or an external contributor.

**Comment by ryanmoran** [comment]
This is now implemented at https://github.com/paketo-community/git.
