### ISSUE TITLE
Implement RFC #0024

### ISSUE THREAD

**Issue by ForestEckhardt** [paketo-buildpacks/rfcs#46]
RFC #0024: https://github.com/paketo-buildpacks/rfcs/blob/main/text/0024-utility-buildpacks-team.md

RFC #0024 has been accepted. This is a issue placeholder for the creation of a new Utility team.

**Comment by ryanmoran** [comment]
This has been done for a while now.

**Comment by ForestEckhardt** [comment]
Then I will move it into the implemented section!
