### ISSUE TITLE
How do we handle superseded RFCs?

### ISSUE THREAD

**Issue by ForestEckhardt** [paketo-buildpacks/rfcs#47]
[RFC #0003](https://github.com/paketo-buildpacks/rfcs/blob/main/text/0003-replace-buildpack-yml.md) which proposed that all buildpacks should do their specific configuration using the Build Plan Buildpack. This RFC was never implemented and instead we have chosen another path using environment variables for all buildpack specific configuration. How should we mark this RFC?

**Comment by arjun024** [comment]
Another RFC to deprecate it, and a header on the subject RFC with link to deprecation RFC?

**Comment by ForestEckhardt** [comment]
I have this as a discussion for the next WG meeting.

**Comment by ForestEckhardt** [comment]
This suspending was done by PR #51
