### ISSUE TITLE
Implement RFC0027: Common Logging Levels for Buildpacks

### ISSUE THREAD

**Issue by ryanmoran** [paketo-buildpacks/rfcs#65]
[RFC](https://github.com/paketo-buildpacks/rfcs/blob/main/text/0027-log-levels.md)

### Summary
All Paketo buildpacks should provide a mechanism for tuning log verbosity. To enable this configuration, the buildpacks should respect a `BP_LOG_LEVEL` environment variable.

* [x] All buildpacks conform to using the `BP_LOG_LEVEL` environment variable to control log levels
* [x] https://github.com/paketo-buildpacks/paketo-website/issues/479

**Comment by dmikusa-pivotal** [comment]
Starting with [libcnb 1.23.0](https://github.com/buildpacks/libcnb/releases/tag/v1.23.0) this is also supported.

**Comment by ForestEckhardt** [comment]
Starting in [packit 2.0.0](https://github.com/paketo-buildpacks/packit/releases/tag/v2.0.0) this is supported for any buildpack using the `scribe` logging package.

**Comment by fg-j** [comment]
@paketo-buildpacks/ruby-maintainers @paketo-buildpacks/nodejs-maintainers @paketo-buildpacks/web-servers @paketo-buildpacks/python-maintainers Please comment below enumerating which buildpacks in your language families do NOT have debug logging.

**Comment by fg-j** [comment]
.NET Core buildpacks without debug logging:
- dotnet-core-runtime
- dotnet-core-aspnet
- dotnet-core-sdk
- icu
- dotnet-execute

**Comment by fg-j** [comment]
Go buildpacks without debug logging:

- [ ] go-dist
- [ ] go-mod-vendor
- [ ] go-build
(Skipping dep and dep-ensure as they'll soon be removed)

All of these are set up to respect the `BP_LOG_LEVEL` env var, but no additional debug logging is in the buildpacks.

**Comment by joshuatcasey** [comment]
PHP buildpacks without debug logging:

- [ ] [php-builtin-server](https://github.com/paketo-buildpacks/php-builtin-server/blob/41303fef25a62ba8d386359c8bfd8648fb7cb038/run/main.go#L12)

**Comment by ForestEckhardt** [comment]
Utility Buildpacks
- [ ]  https://github.com/paketo-buildpacks/git/issues/99
- [ ] https://github.com/paketo-buildpacks/source-removal/issues/42
- [ ] https://github.com/paketo-buildpacks/tini/issues/213

**Comment by ForestEckhardt** [comment]
Web Servers Buildpacks
- [ ] https://github.com/paketo-buildpacks/nginx/issues/406

**Comment by ForestEckhardt** [comment]
Ruby Buildpack
- [ ] https://github.com/paketo-buildpacks/puma/issues/295
- [ ] https://github.com/paketo-buildpacks/thin/issues/284
- [ ] https://github.com/paketo-buildpacks/unicorn/issues/282

**Comment by ForestEckhardt** [comment]
Nodejs Buildpacks
- [ ] https://github.com/paketo-buildpacks/node-start/issues/238
- [ ] https://github.com/paketo-buildpacks/npm-start/issues/229
- [ ] https://github.com/paketo-buildpacks/yarn-start/issues/220
- [ ] https://github.com/paketo-buildpacks/npm-install/issues/390
- [ ] https://github.com/paketo-buildpacks/yarn-install/issues/368
- [ ] https://github.com/paketo-buildpacks/node-module-bom/issues/98
- [ ] https://github.com/paketo-buildpacks/node-run-script/issues/116

**Comment by ForestEckhardt** [comment]
Python Buildpacks
- [ ] https://github.com/paketo-buildpacks/python-start/issues/165

**Comment by sophiewigmore** [comment]
the only aspect left here is documentation.

**Comment by sophiewigmore** [comment]
Documentation has been merged in, we can close this out!
