### ISSUE TITLE
Start Command CNB

### ISSUE THREAD

**Issue by kvedurmu** [paketo-buildpacks/rfcs#7]
CloudFoundry Buildpacks have supported letting user define start commands in their app manifests (see https://docs.cloudfoundry.org/devguide/deploy-apps/manifest-attributes.html#start-commands). It could be useful to have some sort of Paketo implementation of this that could be included in each of our language family CNBs.

**Comment by ForestEckhardt** [comment]
I have thrown together a potential solution to this problem.
https://github.com/ForestEckhardt/entrypoint

**Comment by nebhale** [comment]
Why wouldn’t [`paketo-buildpacks/procfile`](https://github.com/paketo-buildpacks/procfile) satisfy this requirement?

**Comment by kvedurmu** [comment]
Ahh I didn't actually know about the procfile CNB @nebhale. This is exactly what we'd need to accomplish this. I'm going to close this out and file issues in all of the language family CNBs to include procfile in the group ordering.
